version: '3.8'

services:
  db:
    image: postgres:15.3-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env

  web:
    image: hetpahhep/notesnob:latest
    restart: always
    volumes:
      - static_value:/static/
      - media_value:/media/
    depends_on:
      - db
    env_file:
      - ../.env

  nginx:
    image: nginx:1.25.0-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    ports:
      - '80:80'
    depends_on:
      - web

volumes:
  static_value:
  media_value:
  postgres_data: