# Generated by Django 4.2.1 on 2023-05-19 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_title_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='gener',
            new_name='genre',
        ),
    ]
