# Generated by Django 4.2.1 on 2023-05-18 02:06

from django.db import migrations, models

import api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[api.validators.UsernameValidator()]),
        ),
    ]
