# Generated by Django 4.2.1 on 2023-05-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='confirmation_code',
            field=models.CharField(max_length=14),
        ),
    ]
